import { baseApi } from './baseApi.js'

function unwrap(response) {
  return response?.data ?? response
}

export const workforceApi = baseApi.injectEndpoints({
  endpoints: (build) => ({
    getCorporateDashboard: build.query({
      query: () => '/corporate/dashboard',
      transformResponse: unwrap,
      providesTags: ['CorporateDashboard'],
    }),
    getCorporateProjects: build.query({
      query: () => '/corporate/projects',
      transformResponse: unwrap,
      providesTags: ['Projects'],
    }),
    createCorporateProject: build.mutation({
      query: (body) => ({ url: '/corporate/projects', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Projects', 'CorporateDashboard'],
    }),
    getCorporateProject: build.query({
      query: (id) => `/corporate/projects/${id}`,
      transformResponse: unwrap,
      providesTags: (_r, _e, id) => [{ type: 'Projects', id }],
    }),
    addCorporateSite: build.mutation({
      query: ({ projectId, ...body }) => ({
        url: `/corporate/projects/${projectId}/sites`,
        method: 'POST',
        body,
      }),
      transformResponse: unwrap,
      invalidatesTags: ['Projects'],
    }),
    getMyRequests: build.query({
      query: (params) => ({ url: '/workforce/requests', params }),
      transformResponse: unwrap,
      providesTags: ['Requests'],
    }),
    getRequest: build.query({
      query: (id) => `/workforce/requests/${id}`,
      transformResponse: unwrap,
      providesTags: (_r, _e, id) => [{ type: 'Requests', id }],
    }),
    createRequest: build.mutation({
      query: (body) => ({ url: '/workforce/requests', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Requests', 'CorporateDashboard', 'AdminRequests'],
    }),
    createRazorpayOrder: build.mutation({
      query: (id) => ({ url: `/workforce/requests/${id}/payment/order`, method: 'POST' }),
      transformResponse: unwrap,
    }),
    verifyRazorpayPayment: build.mutation({
      query: ({ id, ...body }) => ({
        url: `/workforce/requests/${id}/payment/verify`,
        method: 'POST',
        body,
      }),
      transformResponse: unwrap,
      invalidatesTags: (_r, _e, { id }) => [{ type: 'Requests', id }],
    }),
    createExtraWork: build.mutation({
      query: ({ id, ...body }) => ({ url: `/workforce/requests/${id}/extra-work`, method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: (_r, _e, { id }) => [{ type: 'Requests', id }],
    }),
    getExtraWork: build.query({
      query: (id) => `/workforce/requests/${id}/extra-work`,
      transformResponse: unwrap,
    }),
    updateExtraWorkStatus: build.mutation({
      query: ({ extraWorkId, ...body }) => ({
        url: `/workforce/extra-work/${extraWorkId}/status`,
        method: 'PATCH',
        body,
      }),
      transformResponse: unwrap,
      invalidatesTags: ['Requests'],
    }),
    getCorporateInvoices: build.query({
      query: () => '/corporate/invoices',
      transformResponse: unwrap,
      providesTags: ['Invoices'],
    }),
    patchCorporateMe: build.mutation({
      query: (body) => ({ url: '/corporate/me', method: 'PATCH', body }),
      transformResponse: unwrap,
    }),
    addCorporateDocument: build.mutation({
      query: (body) => ({ url: '/corporate/documents', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['CorporateProfile'],
    }),
    removeCorporateDocument: build.mutation({
      query: (docId) => ({ url: `/corporate/documents/${docId}`, method: 'DELETE' }),
      transformResponse: unwrap,
    }),
    submitCorporateVerification: build.mutation({
      query: () => ({ url: '/corporate/verification/submit', method: 'POST' }),
      transformResponse: unwrap,
      invalidatesTags: ['CorporateProfile', 'BusinessVerification'],
    }),
    getVendorDashboard: build.query({
      query: () => '/vendor/dashboard',
      transformResponse: unwrap,
      providesTags: ['VendorDashboard'],
    }),
    getVendorCrew: build.query({
      query: () => '/vendor/crew',
      transformResponse: unwrap,
      providesTags: ['Crew'],
    }),
    linkVendorCrew: build.mutation({
      query: (body) => ({ url: '/vendor/crew/link', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Crew', 'VendorDashboard'],
    }),
    getVendorJobs: build.query({
      query: () => '/vendor/jobs',
      transformResponse: unwrap,
      providesTags: ['VendorJobs'],
    }),
    acceptVendorJob: build.mutation({
      query: (id) => ({ url: `/vendor/jobs/${id}/accept`, method: 'POST' }),
      transformResponse: unwrap,
      invalidatesTags: ['VendorJobs', 'VendorDashboard', 'Requests'],
    }),
    assignWorkforce: build.mutation({
      query: ({ id, assignments }) => ({
        url: `/vendor/jobs/${id}/assign`,
        method: 'POST',
        body: { assignments },
      }),
      transformResponse: unwrap,
      invalidatesTags: ['VendorJobs', 'VendorDashboard', 'Requests'],
    }),
    getVendorSettlements: build.query({
      query: () => '/vendor/settlements',
      transformResponse: unwrap,
      providesTags: ['Invoices'],
    }),
    getVendorWallet: build.query({
      query: () => '/vendor/wallet',
      transformResponse: unwrap,
      providesTags: ['VendorWallet'],
    }),
    requestVendorWithdrawal: build.mutation({
      query: (body) => ({ url: '/vendor/wallet/withdraw', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['VendorWallet'],
    }),
    getVendorMarketplaceRequests: build.query({
      query: () => '/vendor/requests',
      transformResponse: unwrap,
      providesTags: ['VendorJobs', 'Requests'],
    }),
    acceptMarketplaceRequest: build.mutation({
      query: (id) => ({ url: `/vendor/requests/${id}/accept`, method: 'POST' }),
      transformResponse: unwrap,
      invalidatesTags: ['VendorJobs', 'Requests', 'VendorDashboard'],
    }),
    declineMarketplaceRequest: build.mutation({
      query: (id) => ({ url: `/vendor/requests/${id}/decline`, method: 'POST' }),
      transformResponse: unwrap,
      invalidatesTags: ['Requests', 'VendorJobs', 'VendorDashboard'],
    }),
    patchVendorMe: build.mutation({
      query: (body) => ({ url: '/vendor/me', method: 'PATCH', body }),
      transformResponse: unwrap,
      invalidatesTags: ['VendorProfile'],
    }),
    addVendorDocument: build.mutation({
      query: (body) => ({ url: '/vendor/documents', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['VendorProfile'],
    }),
    removeVendorDocument: build.mutation({
      query: (docId) => ({ url: `/vendor/documents/${docId}`, method: 'DELETE' }),
      transformResponse: unwrap,
    }),
    submitVendorVerification: build.mutation({
      query: () => ({ url: '/vendor/verification/submit', method: 'POST' }),
      transformResponse: unwrap,
      invalidatesTags: ['VendorProfile', 'BusinessVerification'],
    }),
    getLabourAssignments: build.query({
      query: (params) => ({ url: '/workforce/assignments', params }),
      transformResponse: unwrap,
      providesTags: ['Assignments'],
    }),
    respondAssignment: build.mutation({
      query: ({ id, action, labourLat, labourLng }) => ({
        url: `/workforce/assignments/${id}/respond`,
        method: 'PATCH',
        body: { action, labourLat, labourLng },
      }),
      transformResponse: unwrap,
      invalidatesTags: ['Assignments'],
    }),
    checkIn: build.mutation({
      query: (body) => ({ url: '/workforce/attendance/check-in', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Attendance', 'Assignments'],
    }),
    verifyCheckInOtp: build.mutation({
      query: (body) => ({ url: '/workforce/attendance/check-in/verify', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Attendance', 'Assignments'],
    }),
    regenerateCheckInOtp: build.mutation({
      query: (body) => ({ url: '/workforce/attendance/check-in/regenerate-otp', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Attendance'],
    }),
    startWork: build.mutation({
      query: (body) => ({ url: '/workforce/attendance/start-work', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Attendance', 'Assignments'],
    }),
    checkOut: build.mutation({
      query: (body) => ({ url: '/workforce/attendance/check-out', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Attendance', 'Assignments'],
    }),
    getAttendance: build.query({
      query: (params) => ({ url: '/workforce/attendance', params }),
      transformResponse: unwrap,
      providesTags: ['Attendance'],
    }),
    getAttendanceMonitor: build.query({
      query: (params) => ({ url: '/workforce/attendance/monitor', params }),
      transformResponse: unwrap,
      providesTags: ['Attendance'],
    }),
    getAdminRequests: build.query({
      query: (params) => ({ url: '/admin/workforce/requests', params }),
      transformResponse: unwrap,
      providesTags: ['AdminRequests'],
    }),
    patchRequestStatus: build.mutation({
      query: ({ id, ...body }) => ({
        url: `/admin/workforce/requests/${id}/status`,
        method: 'PATCH',
        body,
      }),
      transformResponse: unwrap,
      invalidatesTags: ['AdminRequests', 'Requests'],
    }),
    sendPaymentReminder: build.mutation({
      query: (id) => ({
        url: `/admin/workforce/requests/${id}/reminder`,
        method: 'POST',
      }),
      transformResponse: unwrap,
    }),
    recordOfflinePayment: build.mutation({
      query: (id) => ({
        url: `/admin/workforce/requests/${id}/record-payment`,
        method: 'POST',
      }),
      transformResponse: unwrap,
      invalidatesTags: ['AdminRequests', 'Requests'],
    }),
    releaseVendorSettlement: build.mutation({
      query: (id) => ({
        url: `/admin/workforce/requests/${id}/release-settlement`,
        method: 'POST',
      }),
      transformResponse: unwrap,
      invalidatesTags: ['AdminRequests', 'Requests', 'VendorWallet'],
    }),
    releasePartialSettlement: build.mutation({
      query: ({ id, ...body }) => ({
        url: `/admin/workforce/requests/${id}/release-partial`,
        method: 'POST',
        body,
      }),
      transformResponse: unwrap,
      invalidatesTags: ['AdminRequests', 'Requests', 'VendorWallet'],
    }),
    holdSettlement: build.mutation({
      query: ({ id, ...body }) => ({
        url: `/admin/workforce/requests/${id}/hold`,
        method: 'POST',
        body,
      }),
      transformResponse: unwrap,
      invalidatesTags: ['AdminRequests', 'Requests'],
    }),
    addFinanceNote: build.mutation({
      query: ({ id, ...body }) => ({
        url: `/admin/workforce/requests/${id}/notes`,
        method: 'POST',
        body,
      }),
      transformResponse: unwrap,
      invalidatesTags: ['AdminRequests', 'Requests'],
    }),
    createAllocation: build.mutation({
      query: (body) => ({ url: '/admin/workforce/allocations', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['AdminRequests', 'Assignments', 'VendorJobs'],
    }),
    listCorporateVerifications: build.query({
      query: (params) => ({ url: '/admin/workforce/corporates', params }),
      transformResponse: unwrap,
      providesTags: ['BusinessVerification'],
    }),
    listVendorVerifications: build.query({
      query: (params) => ({ url: '/admin/workforce/vendors', params }),
      transformResponse: unwrap,
      providesTags: ['BusinessVerification'],
    }),
    getCorporateVerificationDetail: build.query({
      query: (id) => `/admin/workforce/corporates/${id}`,
      transformResponse: unwrap,
    }),
    getVendorVerificationDetail: build.query({
      query: (id) => `/admin/workforce/vendors/${id}`,
      transformResponse: unwrap,
    }),
    reviewCorporate: build.mutation({
      query: ({ id, ...body }) => ({
        url: `/admin/workforce/corporates/${id}/review`,
        method: 'PATCH',
        body,
      }),
      invalidatesTags: ['CorporateProfile', 'BusinessVerification'],
    }),
    reviewVendor: build.mutation({
      query: ({ id, ...body }) => ({
        url: `/admin/workforce/vendors/${id}/review`,
        method: 'PATCH',
        body,
      }),
      invalidatesTags: ['VendorProfile', 'BusinessVerification'],
    }),
    generateInvoice: build.mutation({
      query: (body) => ({ url: '/admin/workforce/invoices/generate', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Invoices', 'AdminRequests'],
    }),
    getInvoicesByRequest: build.query({
      query: (requestId) => `/admin/workforce/requests/${requestId}/invoices`,
      transformResponse: unwrap,
      providesTags: (r, e, requestId) => [{ type: 'Invoices', id: requestId }],
    }),
    getAdminPricing: build.query({
      query: () => '/admin/workforce/pricing',
      transformResponse: unwrap,
      providesTags: ['AdminPricing'],
    }),
    upsertPricing: build.mutation({
      query: (body) => ({ url: '/admin/workforce/pricing', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['AdminPricing'],
    }),
    getSystemPricing: build.query({
      query: () => '/admin/workforce/system-pricing',
      transformResponse: unwrap,
      providesTags: ['SystemPricing'],
    }),
    getPublicSystemPricing: build.query({
      query: () => '/workforce/system-pricing',
      transformResponse: unwrap,
      providesTags: ['SystemPricing'],
    }),
    updateSystemPricing: build.mutation({
      query: (body) => ({ url: '/admin/workforce/system-pricing', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['SystemPricing'],
    }),
    getSettlementRules: build.query({
      query: () => '/admin/workforce/settlement-rules',
      transformResponse: unwrap,
      providesTags: ['SystemPricing'],
    }),
    updateSettlementRules: build.mutation({
      query: (body) => ({ url: '/admin/workforce/settlement-rules', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['SystemPricing'],
    }),
    getPricingHistory: build.query({
      query: () => '/admin/workforce/pricing-history',
      transformResponse: unwrap,
      providesTags: ['SystemPricing'],
    }),
    verifyAttendance: build.mutation({
      query: ({ id, ...body }) => ({
        url: `/admin/workforce/attendance/${id}/verify`,
        method: 'PATCH',
        body,
      }),
      transformResponse: unwrap,
      invalidatesTags: ['Attendance'],
    }),
    getQuotation: build.query({
      query: (requestId) => `/corporate/requests/${requestId}/quotation`,
      transformResponse: unwrap,
      providesTags: (r, e, requestId) => [{ type: 'Quotation', id: requestId }],
    }),
    getVendorQuotation: build.query({
      query: (jobId) => `/vendor/jobs/${jobId}/quotation`,
      transformResponse: unwrap,
      providesTags: (r, e, jobId) => [{ type: 'Quotation', id: jobId }],
    }),
    submitQuotation: build.mutation({
      query: ({ id, ...body }) => ({
        url: `/vendor/jobs/${id}/quotation`,
        method: 'POST',
        body,
      }),
      transformResponse: unwrap,
      invalidatesTags: (r, e, { id }) => [{ type: 'Quotation', id: id }, 'VendorJobs', 'Requests'],
    }),
    respondToQuotation: build.mutation({
      query: ({ id, ...body }) => ({
        url: `/corporate/requests/${id}/quotation/respond`,
        method: 'POST',
        body,
      }),
      transformResponse: unwrap,
      invalidatesTags: (r, e, { id }) => [{ type: 'Quotation', id: id }, 'Requests', 'VendorJobs'],
    }),
    getAdminDashboardStats: build.query({
      query: () => '/admin/dashboard/stats',
      transformResponse: unwrap,
      providesTags: ['AdminDashboard'],
    }),
    getAdminDashboardAnalytics: build.query({
      query: () => '/admin/dashboard/analytics',
      transformResponse: unwrap,
      providesTags: ['AdminDashboard'],
    }),
    searchModules: build.query({
      query: (params) => ({ url: '/admin/search', params }),
      transformResponse: unwrap,
    }),
    getNotifications: build.query({
      query: () => '/notifications',
      transformResponse: unwrap,
      providesTags: ['Notifications'],
    }),
    markNotificationRead: build.mutation({
      query: (id) => ({ url: `/notifications/${id}/read`, method: 'PATCH' }),
      transformResponse: unwrap,
      invalidatesTags: ['Notifications'],
    }),
    markAllNotificationsRead: build.mutation({
      query: () => ({ url: '/notifications/read-all', method: 'PATCH' }),
      transformResponse: unwrap,
      invalidatesTags: ['Notifications'],
    }),
    deleteNotification: build.mutation({
      query: (id) => ({ url: `/notifications/${id}`, method: 'DELETE' }),
      transformResponse: unwrap,
      invalidatesTags: ['Notifications'],
    }),
    getAuditLogs: build.query({
      query: (params) => ({ url: '/admin/audit-logs', params }),
      transformResponse: unwrap,
      providesTags: ['AuditLogs'],
    }),
    getTickets: build.query({
      query: (params) => ({ url: '/admin/tickets', params }),
      transformResponse: unwrap,
      providesTags: ['Tickets'],
    }),
    createTicket: build.mutation({
      query: (body) => ({ url: '/admin/tickets', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Tickets'],
    }),
    replyTicket: build.mutation({
      query: ({ id, ...body }) => ({ url: `/admin/tickets/${id}/reply`, method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['Tickets'],
    }),
    closeTicket: build.mutation({
      query: (id) => ({ url: `/admin/tickets/${id}/close`, method: 'PATCH' }),
      transformResponse: unwrap,
      invalidatesTags: ['Tickets'],
    }),
    getSettings: build.query({
      query: () => '/admin/settings',
      transformResponse: unwrap,
      providesTags: ['SystemSettings'],
    }),
    updateSettings: build.mutation({
      query: (body) => ({ url: '/admin/settings', method: 'POST', body }),
      transformResponse: unwrap,
      invalidatesTags: ['SystemSettings'],
    }),
  }),
})

export const {
  useGetCorporateDashboardQuery,
  useGetCorporateProjectsQuery,
  useCreateCorporateProjectMutation,
  useGetCorporateProjectQuery,
  useAddCorporateSiteMutation,
  useGetMyRequestsQuery,
  useGetRequestQuery,
  useCreateRequestMutation,
  useCreateRazorpayOrderMutation,
  useVerifyRazorpayPaymentMutation,
  useCreateExtraWorkMutation,
  useGetExtraWorkQuery,
  useUpdateExtraWorkStatusMutation,
  useGetCorporateInvoicesQuery,
  usePatchCorporateMeMutation,
  useAddCorporateDocumentMutation,
  useRemoveCorporateDocumentMutation,
  useSubmitCorporateVerificationMutation,
  useGetVendorDashboardQuery,
  useGetVendorCrewQuery,
  useLinkVendorCrewMutation,
  useGetVendorJobsQuery,
  useAcceptVendorJobMutation,
  useGetVendorSettlementsQuery,
  useGetVendorWalletQuery,
  useRequestVendorWithdrawalMutation,
  useGetVendorMarketplaceRequestsQuery,
  useAcceptMarketplaceRequestMutation,
  useDeclineMarketplaceRequestMutation,
  useAssignWorkforceMutation,
  usePatchVendorMeMutation,
  useAddVendorDocumentMutation,
  useRemoveVendorDocumentMutation,
  useSubmitVendorVerificationMutation,
  useListCorporateVerificationsQuery,
  useListVendorVerificationsQuery,
  useLazyGetCorporateVerificationDetailQuery,
  useLazyGetVendorVerificationDetailQuery,
  useGetLabourAssignmentsQuery,
  useRespondAssignmentMutation,
  useCheckInMutation,
  useVerifyCheckInOtpMutation,
  useRegenerateCheckInOtpMutation,
  useStartWorkMutation,
  useCheckOutMutation,
  useGetAttendanceQuery,
  useGetAttendanceMonitorQuery,
  useGetAdminRequestsQuery,
  usePatchRequestStatusMutation,
  useSendPaymentReminderMutation,
  useRecordOfflinePaymentMutation,
  useReleaseVendorSettlementMutation,
  useReleasePartialSettlementMutation,
  useHoldSettlementMutation,
  useAddFinanceNoteMutation,
  useCreateAllocationMutation,
  useReviewCorporateMutation,
  useReviewVendorMutation,
  useGenerateInvoiceMutation,
  useGetInvoicesByRequestQuery,
  useGetAdminPricingQuery,
  useUpsertPricingMutation,
  useGetSystemPricingQuery,
  useGetPublicSystemPricingQuery,
  useUpdateSystemPricingMutation,
  useGetSettlementRulesQuery,
  useUpdateSettlementRulesMutation,
  useGetPricingHistoryQuery,
  useVerifyAttendanceMutation,
  useGetQuotationQuery,
  useGetVendorQuotationQuery,
  useSubmitQuotationMutation,
  useRespondToQuotationMutation,
  useGetAdminDashboardStatsQuery,
  useGetAdminDashboardAnalyticsQuery,
  useSearchModulesQuery,
  useGetNotificationsQuery,
  useMarkNotificationReadMutation,
  useMarkAllNotificationsReadMutation,
  useDeleteNotificationMutation,
  useGetAuditLogsQuery,
  useGetTicketsQuery,
  useCreateTicketMutation,
  useReplyTicketMutation,
  useCloseTicketMutation,
  useGetSettingsQuery,
  useUpdateSettingsMutation,
} = workforceApi
